_id: spc_08bcddb0c4054921858bcd7f4a2b6212
type: ApiSpec
parentId: wrk_6cb93e3722ed4533a0fbf6ea74a5d699
modified: 1636450829830
created: 1620980019823
fileName: Supervydejny api v1 - dok
contents: >-
  openapi: "3.0.0"

  info:
    version: "1.0.0"
    title: "Supervýdejny-api-v1"
    description: "Api pro prijem a zpravu zasilek sluzby supervydejny.cz"
    termsOfService:
      "https://supervydejny.cz/terms-and-conditions/"
    contact:
      url: "supervydejny.cz/api/doc"
      email: "support@supervydejny.cz"

  servers:
    - url: "https://supervydejny.cz/api/v1"
      description: "Produkcni server"
    - url: "https://demo.supervydejny.cz/api/v1"
      description: "Testovací server"
  tags:
    - name: "Order"
      description: "Objednávky, balíky, štítky"
    - name: "DeliveryPoints"
      description: "Výdejní místa"
  components:
    schemas:
      ErrorModel:
        type: "object"
        description: "Plný seznam chyb na https://supervydejny.cz/api/doc/error-list"
        properties:
          message:
            type: "string"
          code:
            type: "integer"
      OrderRequest:
        type: "object"
        properties:
          deliveryPointCode:
            type: "string"
          phone:
            type: "string"
          name:
            type: "string"
          surname:
            type: "string"
          email:
            type: "string"
      OrderResponse:
        type: "object"
        properties:
          packageCode:
            type: "string"
          errors:
            type: "array"
            items:
              $ref: '#/components/schemas/ErrorModel'
          warnings:
            type: "array"
            items:
              type: 'string'
      LabelJSONResponse:
        type: "object"
        properties:
          labelCode:
            type: "string"
          deliveryPointCode:
            type: "string"
          customerName:
            type: "string"
          customerSurname":
            type: "string"
      ErrorResponse:
        type: "object"
        description: "Plný seznam chyb na https://supervydejny.cz/api/doc/error-list"
        properties:
          errors:
            type: "array"
            items:
              $ref: '#/components/schemas/ErrorModel'
      DeliveryPoint:
        type: "object"
        properties:
          code:
            type: "string"
          name:
            type: "string"
            nullable: true
          description:
            type: "string"
            nullable: true
          website:
            type: "string"
            nullable: true
          mainPicture:
            type: "string"
          images:
            type: "array"
            items:
              type: "string"
          gps:
            type: "object"
            nullable: true
            properties:
              latitude:
                type: "string"
              longitude:
                type: "string"
          address:
            type: "object"
            properties:
              name:
                type: "string"
              address1:
                type: "string"
              address2:
                type: "string"
                nullable: true
              city:
                type: "string"
              zipCode:
                type: "string"
              country:
                type: "string"
          maxPackageWeight:
            type: "string"
          openingHours:
            type: "string"
            nullable: true
          navigation:
            type: "object"
            properties:
              general:
                type: "string"
                nullable: true
              car:
                type: "string"
                nullable: true
              publicTransport:
                type: "string"
                nullable: true

    securitySchemes:
      ApiKeyAuth:
        description: "Autentifikace tokenem v hlavičce"
        name: "X-AUTH-TOKEN"
        type: "apiKey"
        in: "header"
  paths:
    /order/{packageCode}/label:
      get:
        tags:
          - "Order"
        security:
          - ApiKeyAuth: [ ]
        summary: "Štítek objednávky"
        parameters:
          - name: "packageCode"
            in: path
            required: true
            schema:
              type: "string"
              description: "Kód štítku balíku"
              example: "SUP0000571"
          - name: "Accept"
            description: "Formát odpovědi"
            in: header
            required: false
            schema:
              type: "string"
              enum: [ "image/png", "x-application/zpl", "application/json" ]
              default: "image/png"
        responses:
          "200":
            description: "Obrázek štítku"
            content:
              image/png:
                schema:
                  type: string
                  format: binary
              x-application/zpl:
                schema:
                  type: string
                  format: text
              application/json:
                schema:
                  $ref: '#/components/schemas/LabelJSONResponse'
          "400":
            description: "Bad Request"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  "errors": [
                      "code": 40006,
                      "message": "Supported Mime-types are image/png, application/json and x-application/zpl!"
                  ]
    /public/deliveryPoint:
      get:
        tags:
          - "DeliveryPoints"
        security: [ ]
        summary: "Seznam poboček"
        parameters: [ ]
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: "array"
                  items:
                    $ref: '#/components/schemas/DeliveryPoint'
                example:
                  - "code": "17-CK"
                    "name": "test2UCFljkn"
                    "description": null
                    "website": null
                    "mainPicture": "https://supervydejny.cz/delivery-point/1/image/2"
                    "images": [
                        "https://supervydejny.cz/delivery-point/1/image/1",
                        "https://supervydejny.cz/delivery-point/1/image/2"
                    ]
                    "gps":
                      "latitude": "50.0110703"
                      "longitude": "14.4008111"
                    "address":
                      "name": "Jan Kočí"
                      "address1": "Argentiská 310"
                      "address2": null
                      "city": "Pardubice"
                      "zipCode": "91599"
                      "country": "cze"
                    "maxPackageWeight": "10.00"
                    "openingHours": null,
                    "navigation":
                      "general": null
                      "car": null
                      "publicTransport": null
                  - "code": "77-AA"
                    "name": "Výdejna 2"
                    "description": "popis prodejny"
                    "website": "http://www.example.com"
                    "mainPicture": "https://supervydejny.cz/delivery-point/2/image/1"
                    "images": [
                        "https://supervydejny.cz/delivery-point/2/image/1",
                        "https://supervydejny.cz/delivery-point/2/image/2"
                    ]
                    "gps":
                      "latitude": "50.0110703"
                      "longitude": "14.4008111"
                    "address":
                      "name": "Marek Kočí"
                      "address1": "Stará 333"
                      "address2": "pod schodama"
                      "city": "Benešov"
                      "zipCode": "52989"
                      "country": "cze"
                    "maxPackageWeight": "10.00"
                    "openingHours": "otvírací hodiny"
                    "navigation":
                      "general": "popis cesty"
                      "car": "popis autem"
                      "publicTransport": "popis mhd"
    /order/create:
      post:
        tags:
          - "Order"
        security:
          - ApiKeyAuth: [ ]
        summary: "Vytvoření nové objednávky"
        parameters: [ ]
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRequest'
              example:
                "deliveryPointCode": "VYD0001"
                "phone": "123456789"
                "name": "John"
                "surname": "Doe"
                "email": "john@doe.com"
        responses:
          "201":
            description: "Objednavka vytvorena"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OrderResponse'
          "400":
            description: "Bad Request"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    errors:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/ErrorModel'
                    warnings:
                      type: "array"
                      items:
                        type: "string"
                example:
                  "errors":
                    - "code": 40003
                      "message": "Delivery point with code: testfS7Ws - not found"
                    - "code": 40004
                      "message": "123 - Nesprávný tvar telefonního čísla. Správný formát je např: 123 456 789!"
                    - "code": 40004
                      "message": "john - Zadaný email není ve správném tvaru!!"
                    - "code": 40000
                      "message": "Can not create order. An error has occurred during the process."
                  "warnings":
                    - "Unsupported key loremIpsum"
contentType: yaml
